#ersion: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3306"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: mailhog/mailhog
    ports: ["1025", "8025"]
###< symfony/mailer ###
