
services:

  server:
        image: php:8.2-apache
        build:
            context: .
            dockerfile: ./automation/docker/Dockerfile
        container_name: server
        volumes:
            - ./:/var/www
        networks:
            - MyNetwork    
        links:
            - mysql
        ports:
            - 81:80
        environment:
            DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}?serverVersion=8.2&charset=utf8mb4"
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: green_village
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1

  mysql:
    image: mysql:8.2
    container_name: mysql
    restart: unless-stopped
    environment:
        MYSQL_USER: root
#        MYSQL_PASSWORD: Afpa
        MYSQL_DATABASE: green_village
        MYSQL_ROOT_PASSWORD: password
        MAILER_DSN: smtp://mailhog:1025
    # healthcheck:
    #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #     timeout: 5s
    #     retries: 5
    #     start_period: 60s
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - MyNetwork 
    ports:
      - 3307:3306
  
  phpmyadmin:
          image: phpmyadmin/phpmyadmin
          container_name: phpmyadmin
          depends_on:
             - mysql
          restart: always
          environment:
             PMA_HOST: mysql
            #  PMA_USER: admin
            #  PMA_PASSWORD: Afpa1234
             MYSQL_ROOT_PASSWORD: password
          links:
              - mysql
          networks:
              - MyNetwork 
          ports:
              - 8090:80

  mailhog:
          image: mailhog/mailhog
          ports:
              - 1025:1025
              - 8025:8025          
              
networks:
    MyNetwork: 
         driver: bridge
volumes:
    mysql_data:
  
