services:
  server:
    build:
      context: .
      dockerfile: ./automation/docker/Dockerfile
    container_name: server
    volumes:
      - ./:/var/www/html
    links:
      - mysql
    ports:
      - 81:80
    environment:
      DATABASE_URL: ${DATABASE_URL}

  mysql:
    image: mysql:${MYSQL_VERSION:-8}
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    links:
      - mysql
    ports:
      - 8090:80

volumes:
  mysql_data:

      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

# volumes:
# ###> doctrine/doctrine-bundle ###
#   mysql_data:
###< doctrine/doctrine-bundle ###