
services:

  php:
        build:
            context: .
            dockerfile: ./automation/docker/Dockerfile
        container_name: php
        volumes:
            - ./:/var/www/html
        # networks:
        #     - app_network    
        links:
            - mysql
        ports:
            - 81:80  
        environment:    
          DATABASE_URL: "mysql://root:root_password@mysql:3306/database_name"
          PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1

  mysql:
    image: mysql:8.2
    container_name: mysql
    restart: unless-stopped
    environment:
        MYSQL_USER: admin
        MYSQL_PASSWORD: Afpa
        MYSQL_DATABASE: green_village
        MYSQL_ROOT_PASSWORD: toor
        MAILER_DSN: smtp://mailhog:1025
    # healthcheck:
    #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #     timeout: 5s
    #     retries: 5
    #     start_period: 60s
    volumes:
      - mysql_data:/var/lib/mysql
    # networks:
    #   - app_network
    ports:
      - 3307:3306
  
  phpmyadmin:
          image: phpmyadmin/phpmyadmin
          container_name: phpmyadmin
          # depends_on:
          #    - database
          restart: always
          environment:
             PMA_HOST: mysql
            #  PMA_USER: admin
            #  PMA_PASSWORD: Afpa1234
             MYSQL_ROOT_PASSWORD: toor

          links:
              - mysql
          ports:
              - 8090:80

  mailhog:
          image: mailhog/mailhog
          ports:
              - 1025:1025
              - 8025:8025          
              
# networks:
#     app_network: 
#          driver: bridge
volumes:
    mysql_data:
  
